#!/bin/bash
#
#Algus
#
#Aja teade

echo -e "Sisesta aeg tundides: \c"
read aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
        echo "Hommik!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
        echo "Tere päevast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
        echo "Õhtust."
elif [ $aeg -ge 22 -a $aeg -lt 24 ]; then
        echo "Head ööd!"
elif [ $aeg -ge 24 -a $aeg -lt 6 ]; then
        echo "Tuli aeg  magama!"
else
        echo "error"
fi

#
#Lõpp
#



